title: Prakamya Mishra
name: "Prakamya Mishra"
author: Prakamya Mishra
twitter_username: PrakamyaMishra
baseurl: "/"
description: Documenting my learning notes.
profile_url: "prakamya-mishra.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
